//! Design Tokens Data Model and Multi-Target Compiler
//!
//! Handles serialization, validation, and multi-format compilation
//! (CSS Custom Properties, JSON Schema, Tailwind Theme, Swift, Kotlin, Dart).

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum DomainType {
    Travel,
    Finance,
    Ecommerce,
    Core,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum ThemeMode {
    Light,
    Dark,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ThemeTokens {
    pub primary_color: String,
    pub secondary_color: String,
    pub accent_color: String,
    pub border_radius: u32,
    pub font_family: String,
    pub mode: ThemeMode,
    pub active_domain: DomainType,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ThemePreset {
    pub id: String,
    pub name: String,
    pub domain: DomainType,
    pub tokens: ThemeTokens,
}

impl Default for ThemeTokens {
    fn default() -> Self {
        Self {
            primary_color: "#2563EB".to_string(),
            secondary_color: "#64748B".to_string(),
            accent_color: "#10B981".to_string(),
            border_radius: 8,
            font_family: "Inter, system-ui, -apple-system, sans-serif".to_string(),
            mode: ThemeMode::Light,
            active_domain: DomainType::Travel,
        }
    }
}

impl ThemeTokens {
    /// Compiles active tokens to standardized CSS Custom Properties
    pub fn to_css_variables(&self) -> String {
        let r = self.border_radius;
        format!(
            r#":root {{
  /* Brand Tokens */
  --color-primary: {};
  --color-secondary: {};
  --color-accent: {};

  /* Border Radius Scale */
  --radius-sm: {}px;
  --radius-md: {}px;
  --radius-lg: {}px;
  --radius-xl: {}px;
  --radius-full: 9999px;

  /* Typography */
  --font-family: {};
}}"#,
            self.primary_color,
            self.secondary_color,
            self.accent_color,
            (r / 2).max(2),
            r,
            r + (r / 2),
            r * 2,
            self.font_family
        )
    }

    /// Compiles tokens to a Tailwind CSS theme extension snippet
    pub fn to_tailwind_theme(&self) -> String {
        format!(
            r#"module.exports = {{
  theme: {{
    extend: {{
      colors: {{
        primary: '{}',
        secondary: '{}',
        accent: '{}',
      }},
      borderRadius: {{
        sm: '{}px',
        md: '{}px',
        lg: '{}px',
        xl: '{}px',
      }},
      fontFamily: {{
        sans: ['{}'],
      }}
    }}
  }}
}};"#,
            self.primary_color,
            self.secondary_color,
            self.accent_color,
            (self.border_radius / 2).max(2),
            self.border_radius,
            self.border_radius + (self.border_radius / 2),
            self.border_radius * 2,
            self.font_family
        )
    }

    /// Compiles tokens to Swift (SwiftUI Color Extension)
    pub fn to_swift_colors(&self) -> String {
        format!(
            r#"// Generated by Rustbook Core Engine
import SwiftUI

extension Color {{
    static let brandPrimary = Color(hex: "{}")
    static let brandSecondary = Color(hex: "{}")
    static let brandAccent = Color(hex: "{}")
}}"#,
            self.primary_color, self.secondary_color, self.accent_color
        )
    }

    /// Compiles tokens to Kotlin (Jetpack Compose)
    pub fn to_kotlin_compose(&self) -> String {
        format!(
            r#"// Generated by Rustbook Core Engine
package com.rustbook.designsystem.theme

import androidx.compose.ui.graphics.Color

val BrandPrimary = Color(0xFF{})
val BrandSecondary = Color(0xFF{})
val BrandAccent = Color(0xFF{})"#,
            self.primary_color.trim_start_matches('#'),
            self.secondary_color.trim_start_matches('#'),
            self.accent_color.trim_start_matches('#')
        )
    }

    /// Compiles tokens to Dart (Flutter)
    pub fn to_flutter_dart(&self) -> String {
        format!(
            r#"// Generated by Rustbook Core Engine
import 'package:flutter/material.dart';

class RustbookTheme {{
  static const Color primary = Color(0xFF{});
  static const Color secondary = Color(0xFF{});
  static const Color accent = Color(0xFF{});
  static const double borderRadius = {};
}}"#,
            self.primary_color.trim_start_matches('#'),
            self.secondary_color.trim_start_matches('#'),
            self.accent_color.trim_start_matches('#'),
            self.border_radius
        )
    }
}
